export const ActionTypes = {
    SET_PRODUCTS: "SET_PRODUCTS",
    SELECTED_PRODUCT: "SELECTED_PRODUCT",
    REMOVE_SELECTED_PRODUCT: "REMOVE_SELECTED_PRODUCT",
    UPDATE_PRODUCT: "UPDATE_PRODUCT",
    ADD_PRODUCT: "ADD_PRODUCT",
    LOGIN: "LOGIN",
    LOGOUT: "LOGOUT",
    SIGN_IN: "SIGN_IN",
    TOGGLE_DARKMODE: "TOGGLE_DARKMODE",
}